project:
  type: website
  output-dir: docs

website:
  page-navigation: false
  title: "The International Fossil Coral and Reef Society"
  description: "All things fossil corals, sponges, and reef ecosystems in the broadest sense"
  site-url: https://hackathon.palaeoverse.org
  repo-url: https://github.com/palaeoverse-community/hackathon/
  open-graph: true
  twitter-card: true
  image: "/images/twitter-card.png"
  page-footer:
    border: true
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Lewis A. Jones"
    center:
      - icon: twitter
        href: https://twitter.com/fossil_reef
        aria-label: "Twitter"
    background: "#E0D8D6"

  sidebar:
    background: "#E0D8D6"
    border: true
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: twitter
        href: https://twitter.com/fossil_reef
        text: "Twitter"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: About
        contents:
           - href: team.qmd
             text: Council
           - href: statute.qmd
             text: Statue
           - href: history.qmd
             text: History
      - href: membership.qmd
        text: Membership
      - href: meetings.qmd
        text: Meetings
      - href: gallery.qmd
        text: Gallery
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Gill Sans"
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-title: "Page Contents"
    link-external-newwindow: true
    linkcolor: "red"
    link-external-icon: false
    fontsize: Large

editor: visual